# Generated by Django 3.0.5 on 2020-08-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
