# Generated by Django 3.0.5 on 2020-08-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200821_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_id', models.IntegerField()),
                ('candidate_id', models.IntegerField()),
                ('start_time', models.IntegerField(null=True)),
                ('end_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.IntegerField(null=True),
        ),
    ]
