# Generated by Django 3.0.5 on 2020-08-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200822_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='end_time',
            field=models.IntegerField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='start_time',
            field=models.IntegerField(max_length=70, null=True),
        ),
    ]
